import pandas as pd
import numpy as np

def create_lag_features(df: pd.DataFrame, columns_to_lag: list, lags: list = [1, 5, 15]) -> pd.DataFrame:
    """
    Creates time-shifted (lagged) features for specified columns.
    Ensures that for a row at time t, lag_1 represents the value at t-1.
    """
    df = df.copy()
    for col in columns_to_lag:
        if col not in df.columns:
            continue
        for lag in lags:
            df[f"{col}_lag_{lag}"] = df[col].shift(lag)
    return df

def create_rolling_features(df: pd.DataFrame, mean_cols: list, std_cols: list, windows: list = [5, 15, 30]) -> pd.DataFrame:
    """
    Creates rolling mean and standard deviation features.
    To prevent data leakage of the current timestamp t, we shift the series by 1 
    before calculating the rolling window stats. So rolling statistics represent
    historical intervals (e.g. t-1 down to t-W).
    """
    df = df.copy()
    
    # 1. Rolling Averages
    for col in mean_cols:
        if col not in df.columns:
            continue
        # Shift by 1 first to prevent leakage of the target/current value at index t
        shifted = df[col].shift(1)
        for w in windows:
            df[f"{col}_moving_average_{w}"] = shifted.rolling(window=w, min_periods=1).mean()
            
    # 2. Rolling Standard Deviations
    for col in std_cols:
        if col not in df.columns:
            continue
        shifted = df[col].shift(1)
        for w in windows:
            # fillna(0) for std since std on window=1 is NaN (needs at least 2 points)
            df[f"{col}_std_{w}"] = shifted.rolling(window=w, min_periods=2).std().fillna(0.0)
            
    return df

def create_trend_features(df: pd.DataFrame, columns_to_trend: list) -> pd.DataFrame:
    """
    Calculates the growth rate of resource usage metrics compared to the previous time step.
    Growth rate = (val_t - val_{t-1}) / (val_{t-1} + epsilon)
    """
    df = df.copy()
    epsilon = 1e-5
    for col in columns_to_trend:
        if col not in df.columns:
            continue
        prev_val = df[col].shift(1)
        # Difference divided by previous value (with epsilon to avoid division by zero)
        df[f"{col}_growth_rate"] = (df[col] - prev_val) / (prev_val + epsilon)
    return df

def create_time_features(df: pd.DataFrame, timestamp_col: str = "timestamp") -> pd.DataFrame:
    """
    Extracts time features and encodes cyclical variables (hour, day_of_week) 
    using sine and cosine functions.
    """
    df = df.copy()
    if timestamp_col not in df.columns:
        return df
        
    ts = pd.to_datetime(df[timestamp_col])
    
    # Standard time extractions
    df["hour"] = ts.dt.hour.astype(int)
    df["day_of_week"] = ts.dt.dayofweek.astype(int)
    df["day_of_month"] = ts.dt.day.astype(int)
    df["is_weekend"] = (ts.dt.dayofweek >= 5).astype(int)
    
    # Cyclical Encoding
    # 1. Hour (24-hour cycle)
    df["sin_hour"] = np.sin(2 * np.pi * df["hour"] / 24.0)
    df["cos_hour"] = np.cos(2 * np.pi * df["hour"] / 24.0)
    
    # 2. Day of week (7-day cycle)
    df["sin_day_of_week"] = np.sin(2 * np.pi * df["day_of_week"] / 7.0)
    df["cos_day_of_week"] = np.cos(2 * np.pi * df["day_of_week"] / 7.0)
    
    return df

def apply_feature_engineering_pipeline(df: pd.DataFrame, is_training: bool = True) -> pd.DataFrame:
    """
    Executes the complete feature engineering pipeline in correct order.
    Ensures timestamps are sorted before any rolling or lag computation.
    """
    df = df.copy()
    
    # Ensure dataset is sorted chronologically to prevent temporal data leakage
    if "timestamp" in df.columns:
        df["timestamp"] = pd.to_datetime(df["timestamp"])
        df = df.sort_values(by="timestamp").reset_index(drop=True)
        
    # Feature columns to transform
    lag_cols = ["cpu_usage", "memory_usage", "network_traffic", "active_users"]
    mean_cols = ["cpu_usage", "memory_usage", "network_traffic", "active_users"]
    std_cols = ["cpu_usage", "memory_usage", "network_traffic"]
    trend_cols = ["cpu_usage", "memory_usage", "network_traffic", "active_users"]
    
    # Apply transformations
    df = create_lag_features(df, lag_cols, lags=[1, 5, 15])
    df = create_rolling_features(df, mean_cols, std_cols, windows=[5, 15, 30])
    df = create_trend_features(df, trend_cols)
    df = create_time_features(df, timestamp_col="timestamp")
    
    # Handle NaN values generated by lag/rolling shifts.
    # In training, we drop rows with NaNs since tree models require fully populated matrices.
    # We drop the first 15 rows (maximum lag) to keep data clean.
    if is_training:
        df = df.dropna().reset_index(drop=True)
    else:
        # In inference, if NaNs occur (e.g. history buffer still warming up), we forward fill / backward fill
        # so prediction does not fail.
        df = df.ffill().bfill().fillna(0.0)
        
    return df
